services:
  - type: web
    name: springboot-app
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
