spring.application.name=Movie

tmdb.api.key=c518ae24e43af8bf6f91362a3d312bab
tmdb.base.url=https://api.themoviedb.org/3
tmdb.region=IN

spring.datasource.url=jdbc:postgresql://localhost:5432/departmentservice
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.datasource.driver-class-name=org.postgresql.Driver